version: 2

# Part 1

models:
  - name: transactions_summary_by_customer
    columns:
      - name: customer_id
      - name: full_name
      - name: txn_type
      - name: total_amount
        tests:
          - not_null

# Part 2

  - name: transactions_per_customer_per_month
    columns:
      - name: customer_id
      - name: full_name
      - name: txn_month
        tests:
          - not_null      
      - name: running_transactions_count
        tests:
          - not_null

# Part 3

  - name: incremental_summary
    columns:
      - name: customer_id
      - name: txn_type
      - name: month
      - name: monthly_amount
        tests:
          - not_null